### ISSUE TITLE
Punishments config gets reset on reload

### ISSUE THREAD

**Issue by WoodenAxe** [CubeIsland/AntiGuest#29]
I'm trying to change the punishment for breakblock to occur at 10 and have a different message. So i did this:

```
punishments:
  '3':
    slap:
      damage: 4
  '10':
    kick:
      reason: '&4You were kicked for attempting to break blocks as a guest.'
```

But when i "ag reload" or restart the server it adds the default kick at '5' again.

3.3.0 on 1.2.5-R1.3
